<?php

/**
 * @file
 * Contains code of ui_patterns_legacy module.
 */

declare(strict_types=1);

/**
 * Implements hook_element_info_alter().
 */
function ui_patterns_legacy_element_info_alter(array &$types): void {
  if (isset($types['component'])) {
    $types = _ui_patterns_legacy_clone_component_element($types, "pattern");
    $types = _ui_patterns_legacy_clone_component_element($types, "pattern_preview");
  }
}

/**
 * Clone component element.
 */
function _ui_patterns_legacy_clone_component_element(array $types, string $element_id): array {
  $types[$element_id] = $types['component'];
  array_unshift($types[$element_id]['#pre_render'], 'ui_patterns.component_element_alter:alter');
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('ui_patterns_library') && $element_id === "pattern_preview") {
    array_unshift($types[$element_id]['#pre_render'], 'ui_patterns_library.component_element_alter:alter');
  }
  array_unshift($types[$element_id]['#pre_render'], 'ui_patterns_legacy.component_element_alter:convert');
  return $types;
}
