<?php

/**
 * @file
 * Contains code of ui_patterns_library module.
 */

declare(strict_types=1);

/**
 * @file
 * Contains module file.
 */

/**
 * Implements hook_theme().
 */
function ui_patterns_library_theme(): array {
  return [
    'ui_patterns_overview_page' => [
      'variables' => ['groups' => NULL],
    ],
    'ui_patterns_overview_quicklinks' => [
      'variables' => ['groups' => NULL],
    ],
    'ui_patterns_single_page' => [
      'variables' => ['component' => NULL],
    ],
    'ui_patterns_component_metadata' => [
      'variables' => ['component' => NULL],
    ],
    'ui_patterns_component_table' => [
      'variables' => ['component' => NULL],
    ],
    'ui_patterns_stories_full' => [
      'variables' => ['component' => NULL],
    ],
    'ui_patterns_stories_compact' => [
      'variables' => ['component' => NULL],
    ],
  ];
}

/**
 * Implements hook_element_info_alter().
 */
function ui_patterns_library_element_info_alter(array &$types): void {
  if (isset($types['component'])) {
    array_unshift($types['component']['#pre_render'], 'ui_patterns_library.component_element_alter:alter');
  }
}
